name: "CI"
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
      - name: Install Dependencies
        run: pmpm i --frozen-lockfile
      - name: ESLint
        run: pmpm run lint
      - name: Run Vitest
        run: pmpm run test:coverage
      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: microcms-schema-gen
          json-summary-path: "./packages/microcms-schema-gen/coverage/coverage-summary.json"
          json-final-path: "./packages/microcms-schema-gen/coverage/coverage-final.json"
