name: "CI"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*"]
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: ESLint
        run: pnpm run lint

      - name: Run Vitest
        run: pnpm run test:coverage

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: microcms-schema-gen
          vite-config-path: "./packages/microcms-schema-gen/vitest.config.ts"
          json-summary-path: "./packages/microcms-schema-gen/coverage/coverage-summary.json"
          json-final-path: "./packages/microcms-schema-gen/coverage/coverage-final.json"
